import {StudioViewer} from './studio-viewer.js';
import {reconcileGeneration} from './generation-controls.js';

const $ = (id) => document.getElementById(id);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = v => JSON.parse(JSON.stringify(v));
const fmt = n => Number(n).toLocaleString('en-US', {maximumFractionDigits:0});
const unit = u => u === 'deg' ? '°' : u;
const DEFAULT_CAGE={type:'fitted',dimensions:[9,3,4],padding_mm:30};
const LEGACY_CAGE={type:'box',dimensions:[7,3,4],padding_mm:0};
const CAGE_PRESETS={coarse:[5,3,3],standard:[9,3,4],fine:[13,5,5]};
const state = {lengthLinked:true,bootstrap:null,mode:'shape',model:null,mid:null,analysis:null,baseAnalysis:null,cage:null,lastRegrid:null,parameters:{},controls:[],options:{symmetry:true,preserve_wheels:true,cage:clone(DEFAULT_CAGE)},history:[],cursor:-1,selectedPart:null,compare:false,display:'studio',tab:'parameters',bodyStyle:'fastback',generation:{},lastGen:null,batch:null,variantCache:new Map(),assetThumbs:new Map(),generationTimer:null};
window.miShape = state;
const viewer = new StudioViewer($('main-view'));
const original = new StudioViewer($('baseline-view'));
const thumbnail = new StudioViewer($('thumbnail-host'));
window.miViewer = viewer;
let previewTimer, changeVersion=0, previewApplied=-1, previewRunning=false, loadVersion=0, toastTimer, syncing=false, thumbnailBusy=false, cageRunning=false, cageRequestVersion=0, cageLockedElements=[], displayedCageKey='';

function toast(message,error=false){$('toast').textContent=message;$('toast').className='visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').className='',error?8000:3500);}
function handleError(e){console.error(e);toast(e.message||String(e),true);$('status-text').textContent='需要检查输入';$('live-indicator').classList.remove('busy');}
async function api(path, data, options={}){
 const response=await fetch(path,{...(data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),...options});
 if(!response.ok){let message;try{const e=await response.json();message=typeof e.detail==='string'?e.detail:JSON.stringify(e.detail);}catch{message=`请求失败 (${response.status})`;}throw Error(message);}
 return response.json();
}
function busy(show, message='正在载入多边形模型'){for(const id of ['save','export-open','batch-open'])$(id).disabled=show||!state.mid;$('loading').classList.toggle('hidden',!show);$('loading').querySelector('strong').textContent=message;}
function recipe(){return {parameters:clone(state.parameters),controls:clone(state.controls),options:clone(state.options)};}
function markChanged(){changeVersion++;$('live-indicator').classList.add('busy');$('status-text').textContent='正在计算形态…';clearTimeout(previewTimer);previewTimer=setTimeout(updatePreview,100);saveLocal();}
function checkpoint(){const item=recipe(),key=JSON.stringify(item);if(state.cursor>=0&&JSON.stringify(state.history[state.cursor])===key)return;state.history=state.history.slice(0,state.cursor+1);state.history.push(item);if(state.history.length>60)state.history.shift();state.cursor=state.history.length-1;historyButtons();saveLocal();}
function historyButtons(){$('undo').disabled=cageRunning||state.cursor<=0;$('redo').disabled=cageRunning||state.cursor>=state.history.length-1;}
function assignRecipe(r){state.parameters=clone(r?.parameters||{});state.controls=clone(r?.controls||[]);state.options={symmetry:true,preserve_wheels:true,...clone(r?.options||{})};state.options.cage=clone(r?.options?.cage||LEGACY_CAGE);$('symmetry').checked=state.options.symmetry;$('preserve-wheels').checked=state.options.preserve_wheels;}
function restoreRecipe(r){state.lastRegrid=null;renderRegridReport();assignRecipe(r);refreshParameterValues();syncCageSettings();showControl();markChanged();}
function saveLocal(){if(!state.mid)return;try{localStorage.setItem('mishape-session-v1',JSON.stringify({mid:state.mid,recipe:recipe(),generation:state.generation,bodyStyle:state.bodyStyle,lastGen:state.lastGen,mode:state.mode}));$('save-status').textContent='参数已自动记录 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}catch{$('save-status').textContent='自动记录不可用，请保存工程';}}

function installModel(result,{reset=true}={}){
 state.lastRegrid=null;renderRegridReport();
 state.model=result.model;state.mid=result.model_id;state.analysis=result.analysis;state.baseAnalysis=clone(result.analysis);state.cage=result.cage;state.selectedPart=null;
 if(reset){assignRecipe(result.recipe||{options:{cage:clone(DEFAULT_CAGE)}});state.history=[];state.cursor=-1;}
 displayedCageKey=cageKey(state.options.cage);
 viewer.setModel(result.model);original.setModel(result.model);if(result.vertices)viewer.setVertices(result.vertices);viewer.selected.clear();viewer.explode=0;original.explode=0;viewer.isolate=false;$('isolate').checked=false;$('explode').value=0;
 viewer.setCage($('cage-toggle').checked?result.cage:null);original.setCage(null);
 if(state.compare)original.setCamera(viewer);
 $('model-name').textContent=result.model.name||'MiShape · Parametric GT';
 const source=result.model.metadata?.asset_id;
 $('known-length').value=(result.analysis.measurements.total_length.value/1000).toFixed(3);$('model-subtitle').textContent=source?(result.model.metadata.scale_status==='user_calibrated'?'IMPORTED POLYGON · 原始组件 / 已知车长校准':'IMPORTED POLYGON · 原始组件 / 估计车长校准'):result.model.metadata?.generator?'PARAMETRIC SURFACE · 可重复生成 / 语义组件':'POLYGON MODEL · 米制 / 本地几何';
 $('topology-text').textContent=`${fmt(result.model.vertices.length/3)} VERTICES  ·  ${fmt(result.model.polygons?.length||result.model.faces.length/3)} POLYGONS`;
 state.quality=null;$('quality-text').textContent='原始几何';$('status-text').textContent='模型已就绪 · 拓扑保留';$('live-indicator').classList.remove('busy');
 renderParts();renderMeasurements();renderLandmarkOptions();renderControlOptions();renderMetrics();renderAssets();refreshParameterValues();syncCageSettings();checkpoint();
 if(result.recipe&&!result.vertices&&state.mode==='shape')markChanged();
 if(source&&!state.assetThumbs.has(source)){const data=makeThumbnail(result.model);state.assetThumbs.set(source,data);renderAssets();}
 busy(false);saveLocal();
}
async function loadAsset(id){const token=++loadVersion;changeVersion++;setModeUI('shape');busy(true,'正在打开车辆与多边形组件');try{const result=await api('/api/models/open',{asset_id:id});if(token!==loadVersion)return;installModel(result);toast('已载入真实车辆 · Shift + 拖动控制点开始塑形');}catch(e){if(token===loadVersion){busy(false);handleError(e);}}}
async function updatePreview(){
 if(!state.mid||previewRunning||cageRunning||previewApplied>=changeVersion||state.mode==='generate')return;
 previewRunning=true;const version=changeVersion,mid=state.mid,started=performance.now();
 try{const r=await api(`/api/models/${mid}/deform`,recipe());if(mid!==state.mid||state.mode!=='shape'||cageRunning||version!==changeVersion||version<previewApplied)return;previewApplied=version;
  viewer.setVertices(r.vertices);state.analysis=r.analysis;state.cage=r.cage;state.quality=r.quality;displayedCageKey=cageKey(state.options.cage);viewer.setCage($('cage-toggle').checked?r.cage:null);renderControlOptions();renderCageCount();syncPointAvailability();
  renderMetrics(r.quality);renderMeasurements();$('status-text').textContent=version!==changeVersion?'交互预览 · 正在继续更新…':r.quality?.status==='review'?'几何需要复核 · 打开质量说明':`已更新 · ${Math.round(performance.now()-started)} ms`;
  $('quality-text').textContent=r.quality?.status==='review'?`${r.quality.normal_flips||0} 翻转 / ${r.quality.new_degenerate_faces||0} 新增退化`:'拓扑保留 · 几何已筛查';
  $('quality-text').title=(r.quality?.warnings||[]).join('\n');$('design-tag').textContent=Object.keys(state.parameters).filter(k=>state.parameters[k]).length||state.controls.length?'已修改':'当前设计';
 }catch(e){if(version===changeVersion)handleError(e);}finally{previewRunning=false;if(version!==changeVersion&&previewApplied<changeVersion){updatePreview();}else if(!cageRunning)$('live-indicator').classList.remove('busy');}
}
function syncCamera(from,to){if(syncing||!state.compare)return;syncing=true;to.setCamera(from);syncing=false;}
viewer.onCameraChange=()=>syncCamera(viewer,original);original.onCameraChange=()=>syncCamera(original,viewer);
function makeThumbnail(model,vertices){thumbnail.setModel(model);thumbnail.setCage(null);thumbnail.wire=false;thumbnail.heat=false;thumbnail.materials=true;if(vertices)thumbnail.setVertices(vertices);thumbnail.fit();thumbnail.radius*=.86;thumbnail.draw();return thumbnail.canvas.toDataURL('image/jpeg',.82);}
function renderAssets(){
 const selected=state.model?.metadata?.asset_id;
 $('asset-count').textContent=String(state.bootstrap.assets.length).padStart(2,'0');
 $('asset-list').innerHTML=state.bootstrap.assets.map((a,i)=>`<button class="asset-card ${selected===a.id?'active':''}" data-asset="${esc(a.id)}"><div class="asset-image">${state.assetThumbs.has(a.id)?`<img src="${state.assetThumbs.get(a.id)}" alt="${esc(a.name)}">`:['porsche-930','porsche-carrera-4s'].includes(a.id)?`<img src="/images/${esc(a.id)}.jpg" alt="${esc(a.name)}">`:a.thumbnail?`<img src="/assets/${esc(a.thumbnail)}" alt="${esc(a.name)}">`:`<div class="asset-placeholder">${i===0?'930':'4S'}</div>`}<span class="asset-type">${i===0?'HERITAGE / 1975':'CONTEMPORARY / 911'}</span><span class="asset-check">✓</span></div><div class="asset-info"><strong>${esc(a.name.replace('Porsche 911 · ','911 '))}</strong><small>${fmt(a.polygons||a.triangles||0)} polygons · ${a.parts||'—'} components</small><span class="asset-arrow">↗</span></div></button>`).join('');
 $('asset-list').querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>loadAsset(b.dataset.asset));
}
function renderParts(){const counts=new Map();for(const label of state.model.face_labels)counts.set(label,(counts.get(label)||0)+1);const parts=state.model.parts.filter(p=>counts.has(p.id));$('part-count').textContent=parts.length+' 组件';$('part-list').innerHTML=parts.map(p=>`<button class="part-row" data-part="${p.id}" title="${esc(p.name)}"><span class="swatch" style="background:${esc(p.color||'#9da88d')}"></span><span class="part-name">${esc(p.name)}</span><small>${fmt(counts.get(p.id))}</small></button>`).join('');$('part-list').querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>selectPart(Number(b.dataset.part)));}
function selectPart(id){state.selectedPart=id;viewer.selected=new Set(id===null?[]:[id]);$('part-list').querySelectorAll('[data-part]').forEach(b=>b.classList.toggle('active',Number(b.dataset.part)===id));viewer.draw();}
viewer.onPick=hit=>selectPart(hit.part);
function renderMetrics(q={}){const m=state.analysis?.measurements||{},base=state.baseAnalysis?.measurements||{};for(const [name,key]of[['length','total_length'],['width','vehicle_width'],['height','vehicle_height']]){const v=m[key]?.value;if(v===undefined)continue;$('metric-'+name).innerHTML=`${fmt(v)} <em>mm</em>`;const delta=v-(base[key]?.value??v),el=$('delta-'+name);el.textContent=Math.abs(delta)>.05?`${delta>0?'+':''}${delta.toFixed(1)} mm · 相对原始`:(name==='width'?'包围盒 · 含后视镜':name==='height'?'包围盒 · 离地基准':state.analysis?.scale_calibration?.status==='estimated'?'估计尺度 · 待已知尺寸校准':'基准测量 · 米制尺寸');el.classList.toggle('changed',Math.abs(delta)>.05);}$('metric-shift').innerHTML=`${Number(q.max_displacement_mm||0).toFixed(1)} <em>mm</em>`;}

const groupNames={dimensions:['整车尺寸','DIMENSIONS'],proportions:['轴距与前后悬','PROPORTIONS'],front:['前部造型','FRONT END'],greenhouse:['座舱与玻璃','GREENHOUSE'],rear:['尾部造型','REAR END'],stance:['姿态与离地','STANCE']};
function fieldHTML(f,value){if(f.type==='select')return `<div class="parameter-row"><div class="parameter-label"><strong>${esc(f.label)}</strong><small>${esc(f.label_en)}</small></div><select data-generation-select="${esc(f.id)}">${f.options.map(o=>`<option value="${esc(o.value)}" ${o.value===value?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div>`;return `<div class="parameter-row ${state.mode==='shape'&&value?'changed':''}" data-field="${esc(f.id)}"><div class="parameter-row-top"><div class="parameter-label" title="${esc(f.definition||f.description||'')}"><strong>${esc(f.label)}</strong><small>${esc(f.label_en)}</small></div><div class="parameter-value"><input aria-label="${esc(f.label)} 数值" data-number="${esc(f.id)}" type="number" min="${f.min}" max="${f.max}" step="${f.step}" value="${value}"><small>${esc(unit(f.unit))}</small></div></div><input aria-label="${esc(f.label)}" data-range="${esc(f.id)}" type="range" min="${f.min}" max="${f.max}" step="${f.step}" value="${value}"><div class="range-labels"><span>${f.min}</span><span class="zero">${state.mode==='shape'?'0 · BASELINE':esc(f.unit)}</span><span>${f.max>0&&state.mode==='shape'?'+':''}${f.max}</span></div></div>`;}
function renderParameters(){if(!state.bootstrap)return;const generation=state.mode==='generate';const fields=generation?state.bootstrap.generation.fields:state.bootstrap.parameters;const groups=generation?state.bootstrap.generation.groups.map(g=>({id:g.id,label:g.label,en:g.english})):Object.entries(groupNames).map(([id,[label,en]])=>({id,label,en}));
 $('parameter-eyebrow').textContent=generation?'PARAMETRIC VEHICLE GENERATOR':'KEY DESIGN PARAMETERS';$('parameter-title').textContent=generation?'生成参数':'形态参数';$('parameter-note').innerHTML=generation?'物理尺寸直接输入，单位 <b>m / °</b><br><span>参数改变后自动重生成，保留组件选型。</span>':'相对基准调整，单位 <b>mm / °</b><br><span>已识别轮组保持刚性，参数变化自动更新。</span>';
 let html=generation?`<div class="preset-select"><label>车辆构型 / BODY STYLE</label><select id="body-style">${state.bootstrap.generation.body_styles.map(s=>`<option value="${s.value}" ${state.bodyStyle===s.value?'selected':''}>${esc(s.label)}</option>`).join('')}</select><label class="link-dimensions"><input id="length-linked" type="checkbox" ${state.lengthLinked?'checked':''}>自动联动关联尺寸</label><div id="generation-coupling" class="coupling-note">必要时调整车顶控制段或轮距，并显示实际联动值。</div></div>`:'';
 html+=groups.map((g,i)=>`<details class="parameter-group" ${i<2?'open':''}><summary><span class="group-number">${String(i+1).padStart(2,'0')}</span>${esc(g.label)}<span class="group-en">${esc(g.en)}</span></summary>${fields.filter(f=>f.group===g.id).map(f=>fieldHTML(f,generation?(state.generation[f.id]??f.default):(state.parameters[f.id]||0))).join('')}</details>`).join('');
 if(generation)html+='<div class="generation-action"><button id="generate-now" class="button dark">重新生成车辆 ↗</button><button id="shape-generated" class="button">进入控制笼塑形</button><small>语义组件 · 物理尺寸 · 可重复生成</small></div>';
 $('parameter-groups').innerHTML=html;
 const update=(key,raw,commit)=>{if(cageRunning)return;const f=fields.find(s=>s.id===key),value=Number(raw);if(!Number.isFinite(value)||value<f.min||value>f.max){if(commit)toast(`${f.label} 范围为 ${f.min}–${f.max}`,true);return;}if(generation){if(state.lengthLinked){const adjusted=reconcileGeneration(state.generation,key,value,state.bootstrap.generation);if(adjusted.error){toast(adjusted.error,true);rowRestore(key,state.generation[key]);return;}state.generation=adjusted.values;for(const c of adjusted.changes)rowRestore(c.key,c.to);if(adjusted.changes.length){const detail=adjusted.changes.map(c=>`${fields.find(f=>f.id===c.key)?.label||c.key} ${Number(c.from).toFixed(3)} → ${Number(c.to).toFixed(3)} ${unit(fields.find(f=>f.id===c.key)?.unit||'')}`).join(' · ');$('generation-coupling').textContent='已联动：'+detail;}}else{state.generation[key]=value;}scheduleGeneration();}else{state.parameters[key]=value;markChanged();if(commit)checkpoint();}const row=$('parameter-groups').querySelector(`[data-field="${key}"]`);row.querySelector('[data-range]').value=value;row.querySelector('[data-number]').value=value;row.classList.toggle('changed',!generation&&value!==0);};
 $('parameter-groups').querySelectorAll('[data-range]').forEach(el=>{el.oninput=()=>update(el.dataset.range,el.value,false);el.onchange=()=>update(el.dataset.range,el.value,true);});
 $('parameter-groups').querySelectorAll('[data-number]').forEach(el=>{el.onchange=()=>update(el.dataset.number,el.value,true);});
 $('parameter-groups').querySelectorAll('[data-generation-select]').forEach(el=>el.onchange=()=>{state.generation[el.dataset.generationSelect]=el.value;scheduleGeneration();});
 if(generation){$('length-linked').onchange=()=>{state.lengthLinked=$('length-linked').checked;};$('body-style').onchange=e=>{state.bodyStyle=e.target.value;state.generation=clone(state.bootstrap.generation.presets[state.bodyStyle]);renderParameters();scheduleGeneration();};$('generate-now').onclick=()=>generateNow();$('shape-generated').onclick=()=>{setModeUI('shape');toast('生成模型已作为基准，可继续用控制笼编辑');};}
}
function rowRestore(key,value){const row=$('parameter-groups').querySelector(`[data-field="${key}"]`);if(!row)return;row.querySelector('[data-range]').value=value;row.querySelector('[data-number]').value=value;}
function refreshParameterValues(){if(state.mode==='generate')return;for(const f of state.bootstrap?.parameters||[]){const row=$('parameter-groups').querySelector(`[data-field="${f.id}"]`);if(!row)continue;const value=state.parameters[f.id]||0;row.querySelector('[data-range]').value=value;row.querySelector('[data-number]').value=value;row.classList.toggle('changed',!!value);}}
function setModeUI(mode){if(mode==='shape'){clearTimeout(state.generationTimer);generationVersion++;}state.mode=mode;$('mode-label').textContent=mode==='shape'?'模型塑形':'参数生成';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));renderParameters();setTab('parameters');$('cage-toggle').checked=mode==='shape';viewer.setCage(mode==='shape'?state.cage:null);$('interaction-hint').textContent=mode==='shape'?'拖动旋转 · 滚轮缩放 · Shift + 拖动控制点':'拖动旋转 · 滚轮缩放 · 修改右侧参数自动生成';syncCageSettings();}
function setTab(tab){state.tab=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('parameter-panel').classList.toggle('hidden',tab!=='parameters');$('cage-panel').classList.toggle('hidden',tab!=='cage');$('measure-panel').classList.toggle('hidden',tab!=='measure');if(tab==='cage'&&state.mode==='generate'){toast('先进入「模型塑形」编辑控制笼');}if(tab==='measure')renderMeasurements();}
let generationVersion=0,generationRunning=false;
function scheduleGeneration(){for(const id of ['save','export-open','batch-open'])$(id).disabled=true;generationVersion++;clearTimeout(state.generationTimer);state.generationTimer=setTimeout(generateNow,500);$('live-indicator').classList.add('busy');$('status-text').textContent='等待生成参数…';}
async function generateNow(){if(generationRunning)return;clearTimeout(state.generationTimer);generationRunning=true;const version=generationVersion,token=++loadVersion;busy(true,'正在生成车身、轮组与语义组件');try{const req={body_style:state.bodyStyle,parameters:clone(state.generation)},result=await api('/api/generate',req);if(version!==generationVersion||token!==loadVersion)return;state.lastGen=req;installModel(result);viewer.setCage(null);$('cage-toggle').checked=false;$('model-subtitle').textContent='PARAMETRIC SURFACE · 物理尺寸 / 语义组件 / 配方重放';const q=result.model.metadata?.mishape_generation?.quality||result.model.metadata?.quality;toast(q?.screen_pass===false?'已生成，部分几何需要复核':'参数车辆已生成，可切换塑形继续编辑');}catch(e){if(version===generationVersion){if(state.lastGen&&state.model?.metadata?.source==='generated'){state.bodyStyle=state.lastGen.body_style;state.generation=clone(state.lastGen.parameters);renderParameters();}busy(false);handleError(e);}}finally{generationRunning=false;if(version!==generationVersion&&state.mode==='generate')generateNow();else{$('live-indicator').classList.remove('busy');busy(false);}}}

function renderMeasurements(){const values=state.analysis?.measurements||{},names=Object.fromEntries((state.bootstrap?.parameters||[]).map(p=>[p.id,p.label]));names.wheelbase='轴距';const methods={mesh_bounds:'多边形包围盒',source_landmarks:'素材关键点',user_landmarks:'手动校准',semantic_geometry:'组件几何推断',automatic_estimate:'几何估计'};$('measurement-list').innerHTML=Object.entries(values).map(([key,m])=>`<div class="measurement-row"><div><span>${esc(names[key]||key)}</span><b>${Number(m.value).toFixed(m.unit==='deg'?1:0)} ${unit(m.unit)}</b></div><small title="${esc(m.definition)}">${esc(methods[m.method]||m.method)} · ${m.estimated?'估计值':'几何测量'} · ${m.confidence==='high'?'高':m.confidence==='medium'?'中':'低'}置信</small></div>`).join('');}
const landmarkNames={front_axle:'前轴中心',rear_axle:'后轴中心',front_tip:'车头端点',rear_tip:'车尾端点',front_bumper_lower:'前保险杠下缘',rear_bumper_lower:'后保险杠下缘',windshield_base:'前风挡下缘',windshield_top:'前风挡上缘',rear_glass_base:'后风挡下缘',rear_glass_top:'后风挡上缘',hood_front:'引擎盖前缘',decklid:'尾厢盖',diffusor_start:'扩散器前缘'};
function renderLandmarkOptions(){$('landmark-select').innerHTML=Object.keys(state.baseAnalysis?.landmarks||{}).map(k=>`<option value="${k}">${esc(landmarkNames[k]||k)}</option>`).join('');showLandmark();}
function showLandmark(){const key=$('landmark-select').value,point=state.options.landmarks?.[key]||state.baseAnalysis?.landmarks?.[key]||[0,0,0];['x','y','z'].forEach((a,i)=>$('landmark-'+a).value=Number(point[i]).toFixed(4));}
function renderControlOptions(){const selected=$('control-select').value,points=(state.cage?.points||[]).filter(p=>p.visible!==false);$('control-select').innerHTML=points.map(p=>`<option value="${p.id}">P${String(p.id).padStart(2,'0')} · [${p.index.join(', ')}]</option>`).join('');if(points.some(p=>String(p.id)===selected))$('control-select').value=selected;showControl();}
function showControl(){const id=Number($('control-select').value),c=state.controls.find(c=>c.id===id),d=c?.delta||[0,0,0];['x','y','z'].forEach((a,i)=>$('control-'+a).value=Number(d[i]*1000).toFixed(1));const p=state.cage?.points.find(p=>p.id===id);viewer.activeHandle=cagePointReady()?p?.index:null;viewer.draw();}
function setControl(id,delta,commit=true){if(!cagePointReady()||!state.cage?.points.some(p=>p.id===id&&p.visible!==false))return;if(delta.some(x=>!Number.isFinite(x)||Math.abs(x)>.35)){toast('单点各方向位移限制为 ±350 mm',true);return;}const i=state.controls.findIndex(c=>c.id===id);if(i>=0)state.controls[i]={id,delta};else state.controls.push({id,delta});state.controls=state.controls.filter(c=>c.delta.some(d=>Math.abs(d)>1e-9));showControl();markChanged();if(commit)checkpoint();}
viewer.onHandlePick=index=>{if(!cagePointReady())return;const p=state.cage.points.find(p=>p.index.every((n,i)=>n===index[i]));if(p){$('control-select').value=p.id;setTab('cage');showControl();}};
viewer.onHandleDrag=(index,delta)=>{if(!cagePointReady())return;const p=state.cage.points.find(p=>p.index.every((n,i)=>n===index[i]));if(!p)return;const old=state.controls.find(c=>c.id===p.id)?.delta||[0,0,0];setControl(p.id,old.map((x,i)=>Math.max(-.35,Math.min(.35,x+delta[i]))),false);};
viewer.canvas.addEventListener('pointerup',()=>{if(state.mode==='shape'&&!cageRunning)checkpoint();});

function cageKey(settings){const c=settings||LEGACY_CAGE;return [c.type,...c.dimensions,c.padding_mm].join(':');}
function cagePointReady(){return state.mode==='shape'&&!cageRunning&&displayedCageKey===cageKey(state.options.cage);}
function syncPointAvailability(){for(const id of ['control-select','control-x','control-y','control-z','control-clear'])$(id).disabled=!cagePointReady();}
function renderRegridReport(){
 const report=state.lastRegrid,card=$('cage-regrid-report');card.classList.toggle('hidden',!report);if(!report)return;
 const max=Number(report.max_error_mm),rms=Number(report.rms_error_mm),review=report.requires_review===true||(Number.isFinite(max)&&max>2);
 card.classList.toggle('review',review);$('cage-regrid-title').textContent=review?'上次控制笼迁移 · 局部细节有损失':'上次控制笼迁移 · 形状偏差';
 $('cage-regrid-max').textContent=Number.isFinite(max)?max.toFixed(2)+' mm':'—';$('cage-regrid-rms').textContent=Number.isFinite(rms)?rms.toFixed(2)+' mm':'—';
 const warning=typeof report.warning==='string'?report.warning.trim():'';$('cage-regrid-note').textContent=(warning?warning+' ':'')+'偏差相对于迁移前形状。低密度可能损失局部细节，可撤销或选择更密的控制笼。';
}
function readCageDraft(){return {type:$('cage-type').value,dimensions:['x','y','z'].map(a=>Number($('cage-n'+a).value)),padding_mm:Number($('cage-padding').value)};}
function renderCageCount(){const points=state.cage?.points||[],visible=points.filter(p=>p.visible!==false).length;const kind=state.options.cage?.type==='fitted'?'车身轮廓':'方形';$('cage-point-count').textContent=displayedCageKey!==cageKey(state.options.cage)?'正在切换控制笼…':points.length?`${visible} 个${kind==='车身轮廓'?'边界可编辑':'可编辑'}点 / ${points.length} 个绑定节点`:'正在读取控制点…';}
function syncCageSettings(){const settings=state.options.cage||LEGACY_CAGE;$('cage-type').value=settings.type;['x','y','z'].forEach((a,i)=>$('cage-n'+a).value=settings.dimensions[i]);$('cage-padding').value=settings.padding_mm;const preset=Object.entries(CAGE_PRESETS).find(([,v])=>v.every((n,i)=>n===settings.dimensions[i]));$('cage-density').value=preset?.[0]||'custom';if(!preset)$('cage-advanced').open=true;renderCageCount();updateCageDraftNote();const disabled=cageRunning||state.mode!=='shape'||!state.mid;$('cage-panel').querySelectorAll('button,input,select').forEach(el=>el.disabled=disabled);syncPointAvailability();}
function updateCageDraftNote(){const draft=readCageDraft(),applied=state.options.cage||LEGACY_CAGE,pending=cageKey(draft)!==cageKey(applied);$('cage-apply').textContent=pending?'应用控制笼设置 ↗':draft.type==='fitted'?'重新贴合控制笼 ↗':'重新建立控制笼 ↗';const note=$('cage-settings-note');note.classList.toggle('pending',pending);note.textContent=state.mode!=='shape'?'进入「模型塑形」后，可调整控制笼与控制点。':cageRunning?'正在重建绑定并迁移已有控制点编辑…':pending?`待应用 ${draft.dimensions.join(' × ')} · 现有编辑将迁移到新控制笼，可撤销。`:draft.type==='fitted'?'按车身轮廓布点，改变密度后点击应用；可撤销。':'按方形网格布点，改变密度后点击应用；可撤销。';}
function lockCageEditing(locked){if(locked){cageLockedElements=[...document.querySelectorAll('#cage-panel button,#cage-panel input,#cage-panel select,#parameter-groups button,#parameter-groups input,#parameter-groups select,#measure-panel button,#measure-panel input,#measure-panel select,[data-mode],[data-asset],#undo,#redo,#reset,#import-open,#save,#export-open,#batch-open,#portfolio-nav')].map(el=>({el,disabled:el.disabled}));for(const {el}of cageLockedElements)el.disabled=true;}else{for(const {el,disabled}of cageLockedElements)if(el.isConnected)el.disabled=disabled;cageLockedElements=[];historyButtons();syncPointAvailability();}updateCageDraftNote();}
async function applyCageSettings(){
 if(cageRunning||state.mode!=='shape'||!state.mid)return;
 const settings=readCageDraft(),[nx,ny,nz]=settings.dimensions;
 if(!Number.isInteger(nx)||nx<5||nx>17||![3,5,7].includes(ny)||!Number.isInteger(nz)||nz<3||nz>7||!Number.isFinite(settings.padding_mm)||settings.padding_mm<0||settings.padding_mm>150){toast('节点数范围：纵向 5–17，横向 3 / 5 / 7，竖向 3–7；外扩 0–150 mm。',true);return;}
 checkpoint();clearTimeout(previewTimer);const version=++changeVersion,requestVersion=++cageRequestVersion,mid=state.mid,modelVersion=loadVersion;
 cageRunning=true;lockCageEditing(true);busy(true,'正在贴合车身并重建控制笼');$('live-indicator').classList.add('busy');$('status-text').textContent='正在迁移控制点编辑…';
 try{const result=await api(`/api/models/${mid}/cage`,{...recipe(),cage:settings});if(requestVersion!==cageRequestVersion||mid!==state.mid||modelVersion!==loadVersion||version!==changeVersion)return;
  assignRecipe(result.recipe);state.lastRegrid=result.regrid?clone(result.regrid):null;renderRegridReport();state.cage=result.cage;state.analysis=result.analysis;state.quality=result.quality;displayedCageKey=cageKey(state.options.cage);previewApplied=version;
  viewer.setVertices(result.vertices);viewer.setCage($('cage-toggle').checked?result.cage:null);renderControlOptions();syncCageSettings();renderMeasurements();renderMetrics(result.quality);refreshParameterValues();checkpoint();
  $('status-text').textContent='控制笼已更新 · 原有编辑已迁移';$('quality-text').textContent=result.quality?.status==='review'?'几何需要复核':'拓扑保留 · 控制笼已更新';$('quality-text').title=(result.quality?.warnings||[]).join('\n');
  const detail=result.regrid?.max_error_mm;toast('控制笼已更新，可撤销'+(Number.isFinite(detail)?` · 迁移最大偏差 ${detail.toFixed(2)} mm`:''));
 }catch(e){if(requestVersion===cageRequestVersion&&mid===state.mid)handleError(e);}
 finally{if(requestVersion===cageRequestVersion){cageRunning=false;lockCageEditing(false);busy(false);$('live-indicator').classList.remove('busy');if(previewApplied<changeVersion)updatePreview();}}
}
$('cage-density').onchange=()=>{const dims=CAGE_PRESETS[$('cage-density').value];if(dims)['x','y','z'].forEach((a,i)=>$('cage-n'+a).value=dims[i]);else $('cage-advanced').open=true;updateCageDraftNote();};
for(const id of ['cage-type','cage-padding'])$(id).onchange=updateCageDraftNote;
for(const a of ['x','y','z'])$('cage-n'+a).onchange=()=>{$('cage-density').value='custom';updateCageDraftNote();};
$('cage-apply').onclick=applyCageSettings;

function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exportDesign(format){if(!state.mid||cageRunning)return;const part=$('export-part').checked?state.selectedPart:null;if($('export-part').checked&&part===null&&format!=='json'){toast('先在左侧选择一个组件',true);return;}toast('正在准备导出…');const response=await fetch(`/api/models/${state.mid}/export`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...recipe(),format,part_id:format==='json'?null:part})});if(!response.ok){const e=await response.json();throw Error(e.detail);}downloadBlob(await response.blob(),`MiShape-${state.model.name.replace(/[^\w\u4e00-\u9fa5-]+/g,'-')}${part===null?'':'-part-'+part}.${format}`);$('export-dialog').close();toast(format==='json'?'工程已保存，可直接导入重放':'当前设计已导出');}
async function startBatch(){if(!state.mid||cageRunning)return;const vary=[...$('batch-drivers').querySelectorAll('input:checked')].map(e=>e.value),count=Number($('batch-count').value),seed=Number($('batch-seed').value);if(!vary.length){toast('至少选择一个采样参数',true);return;}if(!Number.isInteger(count)||count<1||count>50||!Number.isInteger(seed)||seed<0){toast('数量应为 1–50，种子应为非负整数',true);return;}$('batch-start').disabled=true;try{const job=await api('/api/batches',{...recipe(),model_id:state.mid,count,seed,strength:Number($('batch-strength').value)/100,vary});state.batch=job;state.batchBase=state.model;state.variantCache.clear();$('portfolio-grid').innerHTML='';$('portfolio-download').classList.add('hidden');$('batch-dialog').close();$('portfolio-dialog').showModal();pollBatch();}catch(e){handleError(e);}finally{$('batch-start').disabled=false;}}
async function pollBatch(){if(!state.batch)return;try{const job=await api(`/api/batches/${state.batch.id}`);state.batch=job;$('portfolio-progress').textContent=`${job.completed} / ${job.count}`;$('portfolio-count').textContent=job.completed;$('portfolio-info').textContent=`种子 ${job.seed} · 分层采样 · 每个变体保留完整模型与参数配方。点击变体可应用继续编辑。`;$('batch-cancel').classList.toggle('hidden',job.status!=='running');for(const item of job.items||[])if(!$('portfolio-grid').querySelector(`[data-variant="${item.index}"]`))addVariantCard(item);renderVariantThumbnails();if(job.status==='running')setTimeout(pollBatch,900);else if(job.status==='complete'){$('portfolio-download').href=`/api/batches/${job.id}/download`;$('portfolio-download').classList.remove('hidden');toast(`${job.count} 个变体已生成`);}else if(job.status==='failed')toast(job.error||'批量生成失败',true);else if(job.status==='cancelled')toast('批量任务已停止');}catch(e){handleError(e);}}
function addVariantCard(item){const div=document.createElement('div');div.className='portfolio-card';div.dataset.variant=item.index;const names=Object.fromEntries(state.bootstrap.parameters.map(p=>[p.id,p.label]));const detail=Object.entries(item.recipe.parameters).filter(([k,v])=>v).slice(0,4).map(([k,v])=>`${names[k]||k} ${v>0?'+':''}${Number(v).toFixed(0)}`).join(' · ');div.innerHTML=`<div class="variant-skeleton">${String(item.index+1).padStart(2,'0')}</div><div class="portfolio-card-content"><strong>${item.name}<span class="apply-variant">应用设计 ↗</span></strong><small>${esc(detail)}</small><small>${item.quality?.status==='review'?'△ 几何待复核':'○ 拓扑保留'}</small></div>`;div.tabIndex=0;div.setAttribute('role','button');div.setAttribute('aria-label','应用变体 '+item.name);div.onclick=()=>applyVariant(item).catch(handleError);div.onkeydown=e=>{if(e.key==='Enter')div.click();};$('portfolio-grid').append(div);}
async function renderVariantThumbnails(){if(thumbnailBusy||!state.batch)return;thumbnailBusy=true;const jid=state.batch.id,model=state.batchBase;try{for(const item of state.batch.items||[]){if(jid!==state.batch?.id)break;if(state.variantCache.has(item.index))continue;const result=await api(`/api/batches/${jid}/variants/${item.index}`);const thumb=makeThumbnail(model,result.vertices);state.variantCache.set(item.index,{...result,thumb});const card=$('portfolio-grid').querySelector(`[data-variant="${item.index}"]`);if(card){const img=document.createElement('img');img.src=thumb;img.alt=item.name;card.querySelector('.variant-skeleton')?.replaceWith(img);}await new Promise(r=>setTimeout(r,10));}$('recent-variants').innerHTML=[...state.variantCache.values()].slice(-3).map(v=>`<img src="${v.thumb}" alt="${v.name}">`).join('');}catch(e){console.warn('thumbnail',e);}finally{thumbnailBusy=false;if(state.batch?.items.some(i=>!state.variantCache.has(i.index)))setTimeout(renderVariantThumbnails,500);}}
async function applyVariant(item){if(!state.batch)return;if(state.mid!==state.batch.model_id){busy(true,'正在恢复组合的基准模型');const model=await api(`/api/models/${state.batch.model_id}`);installModel(model);}setModeUI('shape');restoreRecipe(item.recipe);checkpoint();$('portfolio-dialog').close();toast(`${item.name} 已应用，可继续编辑`);}

document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(cageRunning||b.dataset.mode===state.mode)return;const mode=b.dataset.mode;setModeUI(mode);if(mode==='generate'){if(!Object.keys(state.generation).length)state.generation=clone(state.bootstrap.generation.presets[state.bodyStyle]);renderParameters();generateNow();}else{clearTimeout(state.generationTimer);generationVersion++;markChanged();}});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
document.querySelectorAll('[data-display]').forEach(b=>b.onclick=()=>{state.display=b.dataset.display;document.querySelectorAll('[data-display]').forEach(el=>el.classList.toggle('active',el===b));viewer.wire=state.display==='wire';viewer.heat=state.display==='heat';viewer.buildGroups();viewer.draw();});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el===b));viewer.view(b.dataset.view);});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
$('fit').onclick=()=>viewer.fit();
$('compare').onclick=()=>{state.compare=!state.compare;$('baseline-panel').classList.toggle('hidden',!state.compare);$('compare').classList.toggle('active',state.compare);requestAnimationFrame(()=>{viewer.fit();if(state.compare)original.setCamera(viewer);});};
$('cage-toggle').onchange=()=>viewer.setCage($('cage-toggle').checked?state.cage:null);
$('isolate').onchange=()=>{if($('isolate').checked&&state.selectedPart===null){$('isolate').checked=false;toast('先选择一个组件');return;}viewer.isolate=$('isolate').checked;viewer.draw();};
$('parts-all').onclick=()=>{selectPart(null);viewer.isolate=false;$('isolate').checked=false;viewer.draw();};
$('explode').oninput=()=>{viewer.explode=Number($('explode').value);viewer.draw();};
$('undo').onclick=()=>{if(cageRunning||state.cursor<=0)return;state.cursor--;restoreRecipe(state.history[state.cursor]);historyButtons();};
$('redo').onclick=()=>{if(cageRunning||state.cursor>=state.history.length-1)return;state.cursor++;restoreRecipe(state.history[state.cursor]);historyButtons();};
$('reset').onclick=()=>{if(cageRunning)return;if(state.mode==='generate'){state.generation=clone(state.bootstrap.generation.presets[state.bodyStyle]);renderParameters();scheduleGeneration();return;}restoreRecipe({parameters:{},controls:[],options:{symmetry:true,preserve_wheels:true,cage:clone(state.options.cage)}});checkpoint();toast('已恢复基准形状');};
$('control-select').onchange=showControl;['x','y','z'].forEach(a=>$('control-'+a).onchange=()=>setControl(Number($('control-select').value),['x','y','z'].map(k=>Number($('control-'+k).value)/1000)));
$('control-clear').onclick=()=>setControl(Number($('control-select').value),[0,0,0]);
for(const [id,key]of[['symmetry','symmetry'],['preserve-wheels','preserve_wheels']])$(id).onchange=()=>{state.options[key]=$(id).checked;markChanged();checkpoint();};
$('landmark-select').onchange=showLandmark;
$('landmark-apply').onclick=()=>{const p=['x','y','z'].map(a=>Number($('landmark-'+a).value));if(p.some(x=>!Number.isFinite(x))){toast('请输入有效坐标',true);return;}state.options.landmarks={...state.options.landmarks,[$('landmark-select').value]:p};markChanged();checkpoint();toast('关键点已校准，重新计算当前设计');};
$('scale-apply').onclick=async()=>{if(!state.mid)return;const length=Number($('known-length').value);if(!Number.isFinite(length)||length<=1||length>=20){toast('请输入 1–20 m 之间的已知车长',true);return;}busy(true,'正在校准车辆尺度');changeVersion++;try{const result=await api(`/api/models/${state.mid}/calibrate`,{...recipe(),length_m:length});setModeUI('shape');installModel(result);setTab('measure');toast('当前形状已按已知车长校准，并建立新基准');}catch(e){busy(false);handleError(e);}};
$('save').onclick=()=>exportDesign('json').catch(handleError);$('export-open').onclick=()=>state.mid&&$('export-dialog').showModal();document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportDesign(b.dataset.export).catch(handleError));
$('import-open').onclick=()=>$('import-dialog').showModal();$('import-file').onchange=()=>{const name=$('import-file').files[0]?.name||'选择车辆模型';$('upload-name').textContent=name;if(name.toLowerCase().endsWith('.glb'))$('import-form').elements.up_axis.value='y';};
$('import-form').onsubmit=async e=>{e.preventDefault();const file=$('import-file').files[0];if(!file)return;const form=new FormData(e.currentTarget);form.set('file',file);$('import-dialog').close();busy(true,'正在读取并规范化模型');try{const result=await api('/api/import',undefined,{method:'POST',body:form});setModeUI('shape');installModel(result);toast('模型已导入');}catch(error){busy(false);handleError(error);}};
$('batch-open').onclick=()=>{if(!state.mid)return;if(state.mode==='generate'){toast('当前生成模型将作为变体组合的基准');}$('batch-dialog').showModal();};$('batch-start').onclick=startBatch;
$('batch-strength').oninput=()=>$('strength-value').textContent=$('batch-strength').value+'%';
$('batch-cancel').onclick=()=>state.batch&&api(`/api/batches/${state.batch.id}/cancel`,{}).then(()=>toast('正在停止，已完成的变体仍可查看')).catch(handleError);
$('portfolio-nav').onclick=()=>{if(state.batch)$('portfolio-dialog').showModal();else $('batch-open').click();};
for(const id of ['help','about-quality'])$(id).onclick=()=>{if(id==='about-quality'&&state.quality?.warnings?.length)toast(state.quality.warnings.join(' / '),true);$('help-dialog').showModal();};
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$(e.shiftKey?'redo':'undo').click();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('save').click();}});
async function boot(){try{state.bootstrap=await api('/api/bootstrap');state.generation=clone(state.bootstrap.generation.presets.fastback);renderAssets();renderParameters();const defaults=['vehicle_length','vehicle_width','vehicle_height','windscreen_angle','greenhouse_tapering'];$('batch-drivers').innerHTML=state.bootstrap.parameters.map(f=>`<label><input type="checkbox" value="${f.id}" ${defaults.includes(f.id)?'checked':''}>${esc(f.label)}</label>`).join('');let saved;try{saved=JSON.parse(localStorage.getItem('mishape-session-v1'));}catch{}if(saved?.mid){try{const model=await api(`/api/models/${saved.mid}`);state.generation=saved.generation||state.generation;state.bodyStyle=saved.bodyStyle||'fastback';state.lastGen=saved.lastGen;installModel(model);restoreRecipe(saved.recipe);checkpoint();toast('已恢复上次设计');return;}catch(e){console.warn('session restore',e);}}if(state.bootstrap.assets.length)await loadAsset(state.bootstrap.assets[0].id);else{setModeUI('generate');await generateNow();}}catch(e){busy(false);handleError(e);$('model-name').textContent='无法连接本地引擎';$('model-subtitle').textContent='请运行 MiShape/start.command，或检查终端错误';}}
boot();
